name: Generate Datas 

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Muhammet-Ozcan
          svg_out_path: doc/grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: main
          build_dir: doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
